# -*- coding: utf-8 -*-
"""Deep audit of a generated white site — finds every detectable tell."""
import sys, re, json, hashlib
from pathlib import Path
from collections import Counter

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

site = Path(r"c:\Users\Ixollozi\Cursor\White_generator\output\site_0000_20260401-022831-ae4bf753")
issues: list[str] = []
warnings: list[str] = []

php_files = sorted(site.glob("*.php"))
all_files = sorted(site.rglob("*"))

# ── 1. AI / generator tells ──────────────────────────────────────────
ai_phrases = [
    "feel like humans", "because they did", "receipt drawer",
    "fewer slogans and more receipts", "this text is generated",
    "counsel-approved", "replace with counsel",
    "not legal advice", "reviewers and internal", "non-binding placeholder",
    "AI-generated", "generated by AI", "language model",
    "as an AI", "I'm an AI", "as a language model",
    "lorem ipsum", "dummy text", "sample text",
    "practical draft for review", "internal draft",
    "this document is a practical draft",
]
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore").lower()
    for phrase in ai_phrases:
        if phrase.lower() in txt:
            issues.append(f"AI_TELL: '{phrase}' found in {f.name}")

# ── 2. Repetition analysis (paragraphs across ALL pages) ──────────────
para_counter = Counter()
para_locations: dict[str, list[str]] = {}
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    paras = re.findall(r"<p>(.*?)</p>", txt, re.DOTALL)
    for p in paras:
        clean = re.sub(r"<[^>]+>", "", p).strip()
        if len(clean) > 40:
            key = clean[:250].lower()
            para_counter[key] += 1
            if key not in para_locations:
                para_locations[key] = []
            para_locations[key].append(f.name)

for text, count in para_counter.most_common(20):
    if count > 4:
        files = set(para_locations[text])
        issues.append(f"REPEAT_PARA ({count}x in {len(files)} files): '{text[:80]}...'")
    elif count > 2:
        warnings.append(f"MILD_REPEAT ({count}x): '{text[:80]}...'")

# ── 3. Heading uniformity ────────────────────────────────────────────
h_counter = Counter()
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    for h in re.findall(r"<h[2-4][^>]*>(.*?)</h[2-4]>", txt):
        h_clean = re.sub(r"<[^>]+>", "", h).strip()
        if h_clean:
            h_counter[h_clean] += 1

post_files = [f for f in php_files if f.name.startswith("post-") or f.name.startswith("article-")]
structural_headings = {"Sources", "Reader comments", "Related", "Newsletter"}
for h, c in h_counter.most_common(15):
    if h in structural_headings:
        continue
    if c > len(post_files) * 0.4 and c > 3:
        issues.append(f"UNIFORM_HEADING ({c}x): '{h}'")

# ── 4. Identical file content (JS, CSS) ──────────────────────────────
js_files = sorted(site.rglob("*.js"))
if len(js_files) >= 2:
    hashes = {}
    for jf in js_files:
        h = hashlib.md5(jf.read_bytes()).hexdigest()
        if h in hashes:
            issues.append(f"IDENTICAL_JS: {jf.name} == {hashes[h]}")
        hashes[h] = jf.name

# ── 5. Picsum / stock photo tells ────────────────────────────────────
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    if "picsum.photos" in txt:
        issues.append(f"PICSUM_URL: picsum.photos link exposed in {f.name}")
    if "unsplash.com" in txt:
        warnings.append(f"UNSPLASH_URL: unsplash link in {f.name}")
    if "placeholder.com" in txt:
        issues.append(f"PLACEHOLDER_IMG: placeholder.com in {f.name}")

# ── 6. Footer policy links mismatch ──────────────────────────────────
manifest = site / "build-manifest.json"
vid = ""
if manifest.exists():
    mdata = json.loads(manifest.read_text(encoding="utf-8"))
    vid = mdata.get("vertical_id", "")
    print(f"Vertical: {vid}")
    print(f"Brand: {mdata.get('brand_name','?')}")

for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    if vid == "news":
        if ">Refunds<" in txt or ">Shipping<" in txt:
            issues.append(f"WRONG_POLICY: Refunds/Shipping in news site footer ({f.name})")
    if vid != "clothing":
        if ">Shipping<" in txt and "shipping-policy" in txt:
            issues.append(f"WRONG_POLICY: Shipping link in non-clothing site ({f.name})")

# ── 7. Tracking / data collection exposure ────────────────────────────
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    if "/api/track" in txt:
        issues.append(f"OLD_TRACKING: /api/track endpoint visible in {f.name}")
    if "/api/leads/" in txt:
        issues.append(f"OLD_LEADS_API: /api/leads/ endpoint visible in {f.name}")
    if "/collect" in txt:
        warnings.append(f"TRACKING: /collect endpoint visible in {f.name}")
    if "/forms/" in txt:
        warnings.append(f"FORMS_API: /forms/ endpoint visible in {f.name}")

# ── 8. Template/code leaks ───────────────────────────────────────────
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    if "{{" in txt or "{%" in txt:
        issues.append(f"TEMPLATE_LEAK: unrendered Jinja tokens in {f.name}")
    if "rng." in txt or "random." in txt:
        issues.append(f"CODE_LEAK: Python code in {f.name}")

# ── 9. Meta description quality ──────────────────────────────────────
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    desc_m = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', txt)
    if desc_m:
        desc = desc_m.group(1)
        if "is more than a headline" in desc:
            issues.append(f"META_SELF_REF: description self-references in {f.name}")
        if desc.startswith("An "):
            issues.append(f"META_GRAMMAR: description starts with 'An ' in {f.name}")
        if len(desc) < 20:
            warnings.append(f"META_SHORT: description too short in {f.name}: '{desc}'")
        if len(desc) > 320:
            warnings.append(f"META_LONG: description >320 chars in {f.name}")

# ── 10. Duplicate post titles/slugs ──────────────────────────────────
titles = []
for f in post_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    title_m = re.search(r"<title>(.*?)</title>", txt)
    if title_m:
        titles.append(title_m.group(1).strip())
title_counts = Counter(titles)
for t, c in title_counts.items():
    if c > 1:
        issues.append(f"DUP_TITLE: '{t[:60]}' appears {c} times")

# ── 11. Broken internal links ────────────────────────────────────────
all_filenames = {f.name for f in all_files if f.is_file()}
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    for href in re.findall(r'href="([^"#][^"]*\.php)"', txt):
        href_clean = href.split("?")[0].split("#")[0]
        if not href_clean.startswith("http") and href_clean not in all_filenames:
            warnings.append(f"BROKEN_LINK: {href_clean} referenced in {f.name}")

# ── 12. Legal page tells ─────────────────────────────────────────────
legal_pages = [f for f in php_files if "policy" in f.name or "terms" in f.name]
for f in legal_pages:
    txt = f.read_text(encoding="utf-8", errors="ignore").lower()
    draft_tells = [
        "non-binding", "internal review", "replace with",
        "this document is a practical draft", "practical draft for review",
        "draft policy narrative", "internal draft", "draft for reviewers",
        "not legal advice",
    ]
    for tell in draft_tells:
        if tell in txt:
            issues.append(f"LEGAL_DRAFT_TELL: '{tell}' in {f.name}")

# ── 13. Comment author vs article author collision ────────────────────
for f in post_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    author_m = re.search(r'class="[^"]*author[^"]*"[^>]*>([^<]+)', txt)
    comment_authors = re.findall(r'class="[^"]*comment-author[^"]*"[^>]*>([^<]+)', txt)
    if author_m and comment_authors:
        a_surname = author_m.group(1).strip().split()[-1].lower()
        for ca in comment_authors:
            if a_surname in ca.strip().lower():
                issues.append(f"NAME_COLLISION: comment author '{ca.strip()}' matches article author surname in {f.name}")

# ── 14. Honeypot form fields exposure ────────────────────────────────
for f in php_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    if 'name="company"' in txt and "tabindex" in txt and "-1" in txt:
        issues.append(f"OLD_HONEYPOT: old company+tabindex honeypot in {f.name}")
    if 'name="website"' in txt and 'class="sr-only"' in txt:
        pass

# ── 15. Uniform sentence patterns across posts ───────────────────────
openers = Counter()
for f in post_files:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    paras = re.findall(r"<p>([^<]{20,})", txt)
    for p in paras[:3]:
        clean = re.sub(r"<[^>]+>", "", p).strip()
        first_words = " ".join(clean.split()[:6]).lower()
        openers[first_words] += 1
for opener, c in openers.most_common(10):
    if c > 4:
        issues.append(f"UNIFORM_OPENER ({c}x): '{opener}'")

# ── 16. Schema.org / JSON-LD quality ─────────────────────────────────
for f in php_files[:3]:
    txt = f.read_text(encoding="utf-8", errors="ignore")
    ld_blocks = re.findall(r'<script type="application/ld\+json">(.*?)</script>', txt, re.DOTALL)
    for ld in ld_blocks:
        try:
            data = json.loads(ld)
            if data.get("@type") == "LocalBusiness":
                if not data.get("address"):
                    warnings.append(f"LD_NO_ADDR: LocalBusiness without address in {f.name}")
        except json.JSONDecodeError:
            issues.append(f"LD_INVALID_JSON: broken JSON-LD in {f.name}")

# ── REPORT ────────────────────────────────────────────────────────────
print(f"\n{'='*70}")
print(f"CRITICAL ISSUES ({len(issues)}):")
for i in issues:
    print(f"  [!] {i}")
print(f"\nWARNINGS ({len(warnings)}):")
for w in warnings:
    print(f"  [~] {w}")
print(f"\n{'='*70}")
if not issues:
    print("NO CRITICAL ISSUES FOUND")
else:
    print(f"{len(issues)} issues need fixing")
